version: "3.11"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#    env_file:
#      - ./.env
    environment:
      - DATABASE_HOSTNAME=dpg-cf5s954gqg47vk6epo6g-a.oregon-postgres.render.com
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=jTM3vXwGZMNRsg1uBybaeXQiIeROpBLO
      - DATABASE_NAME=fastapi_na53
      - DATABASE_USERNAME=fastapi_na53_user
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=jTM3vXwGZMNRsg1uBybaeXQiIeROpBLO
      - POSTGRES_DB=fastapi_na53

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: